### ISSUE TITLE
Crossplane Kubernetes Provider does not create the status fields in target k8s cluster

### ISSUE THREAD

**Issue by ashwinshirva** [crossplane-contrib/provider-kubernetes#111]
### What happened?
I am using crossplane claim, XR, composition and kubernetes provider to create a kubernetes custon resource in an target kubernetes cluster. The custom resource is getting created in the target cluster, but only with the spec fields. I have included the status field as well in the managed resource defined in crossplane composition, but looks the kubernetes provider does not create the status part, it creates only the spec part of the custom resource in external cluster

### How can we reproduce it?
Claim YAML

```
apiVersion: example.org/v1alpha1
kind: MyCr
metadata:
  namespace: default
  name: my-cr-1
spec:
  parameters:
    field2: "sample field2"
  compositionRef:
    name: mycrcomposition
  writeConnectionSecretToRef:
    name: mymy-cr-1-details
```
XRD YAML:

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmycrs.example.org
spec:
  group: example.org
  names:
    kind: XMyCr
    plural: xmycrs
  claimNames:
    kind: MyCr
    plural: mycrs
  connectionSecretKeys:
  - hostname
  defaultCompositionRef:
    name: mycrcomposition
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  field2:
                    type: string
                required:
                - field2
            required:
            - parameters
          status:
            type: object
            properties:
              phase:
                description: Phase that the CR is in currently.
                type: string
```

Composition YAML
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mycrcomposition
  labels:
    crossplane.io/xrd: xmycr.example.org
    crtype: myresource
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XMyCr
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: myresource
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      metadata:
        name: myresource-sample-3
        namespace: "default"
      spec:
        forProvider:
          manifest:
            apiVersion: example.com/v1
            kind: MyResource
            metadata:
              name: myresource-sample-3
              namespace: default
            spec:
              field1: "value1"
              field2: "value2"
            status:
              message: "Sample status message"
              phase: "Running"
        providerConfigRef:
          name: kubernetes-provider

    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.field2
      toFieldPath: spec.forProvider.manifest.spec.field2

      policy:
        fromFieldPath: Required
    readinessChecks:
    - type: None

```

Custom Resource Definition (CRD):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.example.com
spec:
  group: example.com
  names:
    kind: MyResource
    singular: myresource
    plural: myresources
    shortNames:
      - mr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: string
              required:
                - field1
                - field2
            status:
              type: object
              properties:
                message:
                  type: string
                phase:
                  type: string
              required:
                - message
                - phase

```

Custom resource created by kubenetes provider in target cluster:

```
apiVersion: example.com/v1
kind: MyResource
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"example.com/v1","kind":"MyResource","metadata":{"name":"myresource-sample-3","namespace":"default"},"spec":{"field1":"value1","field2":"sample
      field2"},"status":{"message":"Sample status message","phase":"Running"}}'
  creationTimestamp: "2023-04-14T05:57:03Z"
  generation: 1
  name: myresource-sample-3
  namespace: default
  resourceVersion: "1510249"
  uid: fb17b130-2f11-4388-89ee-39e1d0e23dc0
spec:
  field1: value1
  field2: sample field2
```

### What environment did it happen in?
* Crossplane version: v1.10.3
* Kubernetes version : 
**Crossplane Machine:** v1.18.3
**Target Machine:** v1.25.8
* Kubernetes distribution:
**Crossplane Machine:** Minikube
**Target Machine:** Microk8s

* OS (e.g. from /etc/os-release)
**Target Machine:**
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
**Crossplane Machine:**
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

* Kernel (e.g. `uname -a`)
**Crossplane Machine:** Linux sm-dev 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Target Machine:** Linux dev-machine 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
