### ISSUE TITLE
How to authenticate between cross-account-eks-cluster

### ISSUE THREAD

**Issue by ashishvaishno** [crossplane-contrib/provider-kubernetes#121]
Hello All,

I wanted to understand what is the recommended way authenticate k8s provider to provision k8s resources on a cross-account-eks-cluster. 
I am trying to create the k8s config to setup my [provider config](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/provider/config.yaml#L10). 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxx
    server: xxxxxx
  name: cross-account-eks-cluster
contexts:
- context:
    cluster: cross-account-eks-cluster
    user: cross-account-eks-cluster
  name: cross-account-eks-cluster
current-context: cross-account-eks-cluster
kind: Config
preferences: {}
users:
- name: cross-account-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - --region
        - xxxxx
        - eks
        - get-token
        - --cluster-name
        - cross-account-eks-cluster
```
But I noticed that the aws cli is not installed in the image used by k8s-provider pod. 
```
2023-05-31T11:13:06.648Z	DEBUG	provider-kubernetes	Cannot connect to provider	{"controller": "managed/object.kubernetes.crossplane.io", "request": "/xxxxxx-qbx82-wx525", "uid": "a26bad78-97ee-4af4-bc53-7c4cc33b965a", "version": "5789603", "external-name": "xxxxxx-qbx82-wx525", "error": "cannot create new Kubernetes client: cannot create Kubernetes client: Get \"https://xxxxxx.eks.amazonaws.com/api?timeout=32s\": getting credentials: exec: executable aws not found\n\nIt looks like you are trying to use a client-go credential plugin that is not installed.\n\nTo learn more about this feature, consult the documentation available at:\n      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins", "errorVerbose": "Get \"https://xxxxxx.eks.amazonaws.com/api?timeout=32s\": getting credentials: exec: executable aws not found\n\nIt looks like you are trying to use a client-go credential plugin that is not installed.\n\nTo learn more about this feature, consult the documentation available at:\n      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins\ncannot create Kubernetes client\ngithub.com/crossplane-contrib/provider-kubernetes/internal/clients.NewKubeClient\n\tgithub.com/crossplane-contrib/provider-kubernetes/internal/clients/client.go:38\ngithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object.(*connector).Connect\n\tgithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object/object.go:174\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/reconciler/managed/reconciler.go:213\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/reconciler/managed/reconciler.go:761\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235\nruntime.goexit\n\truntime/asm_amd64.s:1594\ncannot create new Kubernetes client\ngithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object.(*connector).Connect\n\tgithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object/object.go:176\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/reconciler/managed/reconciler.go:213\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/reconciler/managed/reconciler.go:761\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v0.19.0/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235\nruntime.goexit\n\truntime/asm_amd64.s:1594"}
```

May be I am missing something here. Or shall I think of using client certificate for authentication between the 2 eks cluster?

Regards
Ashish

**Comment by ashishvaishno** [comment]
@bobh66 The target cluster was not deployed via crossplane.

**Comment by ashishvaishno** [comment]
I installed the latest version of crossplane to try observe only resource, but it doesn't have the alpha feature flag --enable-alpha-management-policies 😕
```
k exec -it -n crossplane-system crossplane-5697555f88-qtl9h -c crossplane -- crossplane --version
v1.12.1
```
```
k exec -it -n crossplane-system crossplane-5697555f88-qtl9h -c crossplane -- crossplane core start --help
Usage: crossplane core start

Start Crossplane controllers.

Flags:
  -h, --help                               Show context-sensitive help.
  -d, --debug                              Print verbose logging statements.
  -v, --version                            Print version and quit.

      --profile=host:port                  Serve runtime profiling data via HTTP at /debug/pprof.
  -n, --namespace="crossplane-system"      Namespace used to unpack and run packages ($POD_NAMESPACE).
      --service-account="crossplane"       Name of the Crossplane Service Account ($POD_SERVICE_ACCOUNT).
  -c, --cache-dir="/cache"                 Directory used for caching package images ($CACHE_DIR).
  -l, --leader-election                    Use leader election for the controller manager ($LEADER_ELECTION).
  -r, --registry="index.docker.io"         Default registry used to fetch packages when not specified in tag ($REGISTRY).
      --ca-bundle-path=STRING              Additional CA bundle to use when fetching packages from registry ($CA_BUNDLE_PATH).
      --webhook-tls-secret-name=STRING     The name of the TLS Secret that will be used by the webhook servers of core Crossplane and providers ($WEBHOOK_TLS_SECRET_NAME).
      --webhook-tls-cert-dir=STRING        The directory of TLS certificate that will be used by the webhook server of core Crossplane. There should be tls.crt and tls.key files ($WEBHOOK_TLS_CERT_DIR).
      --user-agent="crossplane/v1.12.1"    The User-Agent header that will be set on all package requests ($USER_AGENT).
  -s, --sync-interval=1h                   How often all resources will be double-checked for drift from the desired state.
      --poll-interval=1m                   How often individual resources will be checked for drift from the desired state.
      --max-reconcile-rate=10              The global maximum rate per second at which resources may checked for drift from the desired state.
      --esstls-secret-name=STRING          The name of the TLS Secret that will be used by Crossplane and providers as clients of External Secret Store plugins ($ESS_TLS_SECRET_NAME).
      --esstls-certs-dir=STRING            The path of the folder which will store TLS certificates to be used by Crossplane and providers for communicating with External Secret Store plugins ($ESS_TLS_CERTS_DIR).

Alpha Features:
  --enable-environment-configs                      Enable support for EnvironmentConfigs.
  --enable-external-secret-stores                   Enable support for External Secret Stores.
  --enable-composition-functions                    Enable support for Composition Functions.
  --enable-composition-webhook-schema-validation    Enable support for Composition validation using schemas.
```
```
k describe po -n crossplane-system crossplane-5697555f88-qtl9h | grep -i image
    Image:         crossplane/crossplane:v1.12.1
```

**Comment by bobh66** [comment]
Observe Only Resources is a provider feature - core Crossplane does not implement the feature.  Each provider has to be updated to support the feature and add the feature flag.

**Comment by ashishvaishno** [comment]
@bobh66 Provider doesn't support args
```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-aws-provider
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.35.0
  controllerConfigRef:
    name: aws-controller-config
  args:
    - --enable-alpha-management-policies
```
On applying the above
```
unknown field "args" in io.crossplane.pkg.v1.Provider.spec
```

Whereas passing the same in ControllerConfig also doesn't work 
```
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-controller-config
  annotations:
    eks.amazonaws.com/role-arn: xxxx
spec:
  serviceAccountName: crossplane-aws-provider
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
    - --enable-alpha-management-policies
```
logs of provider pod:
```
k logs -n crossplane-system crossplane-aws-provider-c757062bcb4a-67f6f748cd-lnmpj --tail 10 -f
provider: error: unknown long flag '--enable-alpha-management-policies', try --help
```
Or May be I am doing it wrong 🙈

**Comment by ashishvaishno** [comment]
With ClusterAuth and cross account IAM role. I was able to authenticate my crossplane managed cluster 😄 Closing the issue

**Comment by Art3mK** [comment]
@ashishvaishno 👋 I'm trying to figure out the same thing now, could you post any details on how to achieve that? 🙏 Documentation is surprisingly non-existent 😭

**Comment by Art3mK** [comment]
figured it out in a few hours 🫠 So basically one needs this (assuming you are using IRSA for the provider-aws, and have separate IAM role, which could access target cluster. That role must be assumable by the IAM role used by provider-aws via IRSA)

```yaml
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: example-dev-k8s-access
spec:
  assumeRoleChain:
    - roleARN: "arn:aws:iam::123456789101:role/crossplane-example-dev-access-poc"
  credentials:
    source: IRSA
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: example-dev
spec:
  forProvider:
    clusterName: example-dev-euw1-01
    region: eu-west-1
  providerConfigRef:
    name: example-dev-k8s-access
  writeConnectionSecretToRef:
    name: example-dev-cluster-conn
    namespace: crossplane
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example-dev-k8s-access
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: example-dev-cluster-conn
      key: kubeconfig
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: dev-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: crossplane-poc-from-poc-cluster
  providerConfigRef:
    name: example-dev-k8s-access

```
