### ISSUE TITLE
"patchesFrom" dependency blocks managed resource deletion

### ISSUE THREAD

**Issue by yogeek** [crossplane-contrib/provider-kubernetes#138]
### What happened?

A composition is creating multiple resources :
- 1 Namespace
- 1 Release (Helm provider) that includes a k8s service
- 1 Object (K8S provider) that references this service to patch some fields

Extract of the composition :
```
     spec:
        references:
          # Use dependsOn to wait for the VCluster service to exist
          - dependsOn:
              apiVersion: v1
              kind: Service
              name: # patched
              namespace: # patched
          # Patch the VirtualService destination host from the VCluster service name
          - patchesFrom:
              apiVersion: v1
              kind: Service
              name: # patched
              namespace: # patched
              fieldPath: metadata.name
            toFieldPath: spec.tls[0].route[0].destination.host
```

All is ok when I create an claim.
But when I delete the claim, the Release (and also the included Service) is deleted before the Object 2, and the Object 2 deletion is blocked with the message

```
Events:
  Type     Reason                         Age                 From                                     Message
  ----     ------                         ----                ----                                     -------
  Normal   DeletedExternalResource        14s                 managed/object.kubernetes.crossplane.io  Successfully requested deletion of external resource
  Warning  CannotObserveExternalResource  6s (x7 over 7h27m)  managed/object.kubernetes.crossplane.io  cannot resolve resource references: cannot get referenced resource: services "vc-vc1-d6lsq" not found
```

I may add that the corresponding external resource (VirtualService) is deleted correctly (mabe because the namespace, that is also included in the composition is deleted...), it is just the managed crossplane resource that is blocked.

It is intentional ? If it is, how should I configure this kind of dependency to not block the deletion ?

### What environment did it happen in?
Crossplane version: 1.12.1
Crossplane Kubernetes provider: 0.9.0
