### ISSUE TITLE
Managed Resource that could copy object from control plane to remote clusters

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-kubernetes#16]
### What problem are you facing?

While building platform configurations with Crossplane, it is quite common that we need to copy some objects from the local cluster (a.k.a control plane) to remote clusters. The most common examples of this are distributing secrets like dockerhub & helm repo credentials or copying connection creds of a managed resource (e.g. db) to a remote cluster (i.e. application cluster).

This was asked a couple of times in the Crossplane slack and the best solution (workaround?) we have so far is using provider-helm's `set.valueFrom .secretKeyRef`: https://crossplane.slack.com/archives/CEG3T90A1/p1629975361008800?thread_ts=1629969149.007900&cid=CEG3T90A1

There is also an [open issue in Crossplane](https://github.com/crossplane/crossplane/issues/2099) which could be used as a solution here as a composition patch but may not help if a composition is not used or a whole objected needs to be copied.

### How could Crossplane help solve your problem?

Currently provider Kubernetes seems to be the best fit to implement/support this in the form of a managed resource. 

I came up of something like the following after a quick thought:

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: sample-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: regcred
        namespace: application
    from:
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: crossplane-system
      fieldPaths: 
        - type
        - data
```

**Comment by morningspace** [comment]
Looks like an interesting scenario and another nice reason to introduce the use of provider-kubernetes :-)

While instead of inventing a new `from` field, I'm thinking if it makes sense to reuse the idea of [Generic References](https://github.com/crossplane/crossplane/pull/2385). With that, it could be represented as below:
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: sample-namespace
spec:
  references:
  - fromObject:
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: crossplane-system
      fieldPath: data
    toFieldPath: spec.forProvider.manifest.data
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: regcred
        namespace: application
      type: Opaque
```

Still not ideal in this specific case, e.g.: have to specify GVK in two different places. Also, need a way to differentiate whether the object being referenced comes from local or remote cluster. But on the other hand, it gives user the flexibility to copy stuff from more than one sources, not just one-to-one copy.

@turkenh
