### ISSUE TITLE
OwnerReference not added to kubernetes resources

### ISSUE THREAD

**Issue by jonnylangefeld** [crossplane-contrib/provider-kubernetes#18]
I created a composition as attached that is just supposed to create a namespace when a `project.example.com` resource is created.

The resulting namespace is created as expected, however it doesn't have an owner reference set. That means when I delete my `project.example.com` resource, the provisioned namespace remains on the cluster.

It should have the owner reference set so that it gets cleaned up by the kubernetes garbage collector once the composite `objects.kubernetes.crossplane.io` resource is gone.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeprojects.example.com
  labels:
    provider: me
spec:
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: CompositeProject
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
    - name: namespace
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
            metadata:
              name: ""
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: PatchSet
          patchSetName: metadata
        - fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.annotations[paas.getcruise.com/repos]"
        - fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
```
