### ISSUE TITLE
Objects persist after the cluster where they are applied is removed

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-kubernetes#20]
### What happened?

If a cluster is removed, `object` resources that were applied to that cluster tend to persist and cannot be removed.

### How can we reproduce it?

1. Create a composite resource that create a k8s cluster and applies `object` resources from the Kubernetes provider.
2. Delete the composite resource
3. Observe that some `object` resources persist and cannot be deleted from the management cluster.

Here's an example of an XRD that combines AWS and Kubernetes resources.

### What environment did it happen in?

Reproducible with any version.

**Comment by WimDiepgrond** [comment]
We have the same issue.
When I describe the Object resources it states that the secret can't be found. The secret is actually the secret holding the access credentials for the kubernetes API of the cluster. The secret seems to be already deleted by crossplane before all Objects needing it are deleted.

**Comment by Crayeth** [comment]
I believe we're witnessing the same problem. Lol Hi @WimDiepgrond 
Some of the objects report the following, is the secret containing the credentials deleted before/whilst other delete operations are still ongoing?

```
  conditions:
  - lastTransitionTime: "2021-12-16T08:39:48Z"
    message: 'connect failed: cannot get credentials: cannot get credentials secret:
      Secret "dev1" not found'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2021-12-16T08:33:36Z"
    reason: Deleting
    status: "False"
    type: Ready
 ```
