### ISSUE TITLE
Watch changes in the referenced objects

### ISSUE THREAD

**Issue by turkenh** [crossplane-contrib/provider-kubernetes#212]
### What problem are you facing?

Today, it is possible to reference k8s objects in the control plane API by with `spec.references` field. For example, the following manifest will read the ConfigMap named `foo` in the default namespace and propagate it to another cluster/namespace.

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo-copy
spec:
  references:
  # Use patchesFrom to patch field from other k8s resource to this object
  - patchesFrom:
      apiVersion: v1
      kind: ConfigMap
      name: foo
      namespace: default
      fieldPath: data
    toFieldPath: data
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
  providerConfigRef:
    name: another-cluster
```

This problem is that if the ConfigMap foo on the control plane changes, it takes up to the poll interval (up to 10mins by default) for it to be propagated again. 

This sounds similar to https://github.com/crossplane-contrib/provider-kubernetes/issues/159 but different since here were proposing the objects that are part of the desired state. That issue wants to be aware of changes in the observed state as soon as possible by watching them.

### How could Crossplane help solve your problem?

Watch changes in the referenced objects so that updates on the referenced object reconciled immediately instead of waiting for the poll interval.
