### ISSUE TITLE
Object patches failing when Secret redaction is enable

### ISSUE THREAD

**Issue by dariozachow** [crossplane-contrib/provider-kubernetes#216]
### What happened?

I've tried to redact all Secret data in the objects by using the the '--santize-secrets' for the provider. But now my Object errors, when trying to access the status.atProvider.manifest.data[ca.crt] field

### How can we reproduce it?
I have 2 Objects, one creates a Serviceaccount-Token Secret in another cluster and looks like this

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: my-object
  annotations:
    crossplane.io/composition-resource-name: secret-sa-token
    crossplane.io/external-create-pending: '2024-03-15T12:24:58Z'
    crossplane.io/external-create-succeeded: '2024-03-15T12:24:58Z'
    crossplane.io/external-name: my-object
status:
  atProvider:
    manifest:
      apiVersion: v1
      data:
        redacted: null
      kind: Secret
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: >-
            {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"kubernetes.io/service-account.name":"secret-store-sa"},"name":"sa-secret","namespace":"my-namespace"},"type":"kubernetes.io/service-account-token"}
          kubernetes.io/service-account.name: secret-store-sa
          kubernetes.io/service-account.uid: f6e32098-8547-4989-b0df-459379441c78
        creationTimestamp: '2024-03-15T12:24:58Z'
        name: sa-secret
        namespace: my-namespace
      type: kubernetes.io/service-account-token
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          kubernetes.io/service-account.name: secret-store-sa
        name: sa-secret
        namespace: my-namesapce
      type: kubernetes.io/service-account-token
  managementPolicies:
    - '*'
  providerConfigRef:
    name: kubernetes-extern
```
This Object works fine with and without the given flag.
The Problem comes up with the second object which looks like following:

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
   name: my-object-2
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2024-03-18T07:21:05Z'
      message: >-
        observe failed: cannot resolve resource references: cannot patch from
        referenced resource: status.atProvider.manifest.data[ca.crt]: no such
        field
      reason: ReconcileError
      status: 'False'
      type: Synced
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: my-store
        namespace: my-namespace
      spec:
        provider:
          kubernetes:
            auth:
              token:
                bearerToken:
                  key: token
                  name: sa-token-sync
            remoteNamespace: my-namespace
            server:
              url: ""
  managementPolicies:
    - '*'
  providerConfigRef:
    name: kubernetes-in-cluster
  readiness:
    policy: SuccessfulCreate
  references:
    - patchesFrom:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        fieldPath: status.atProvider.manifest.data["ca.crt"]
        kind: Object
        name: my-object-2
      toFieldPath: spec.provider.kubernetes.server.caBundle
```

### What environment did it happen in?
Crossplane version: 1.14.4
provider-kubernetes: 0.12.1
Kubernetes version:
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3

Kubernetes distribution: EKS

**Comment by jonasz-lasut** [comment]
Hi @dariozachow, thank you for the detailed report with both manifests, and apologies that it sat unanswered this long — we're working through the backlog.

This is working as designed, and there is a supported pattern for exactly your setup — verified end-to-end below.

## Why the patch fails — confirmed (code) + reproduced (kind, `SANITIZE_SECRETS=true`)

`--sanitize-secrets` exists to keep secret material out of Object **status** — status is readable by anyone with Object read RBAC and leaks into traces, logs, and GitOps diffs. With the flag on, the provider replaces the *entire* `data` field of a Secret-wrapping Object's `status.atProvider.manifest` with a redaction marker before writing status ([`setAtProvider` → `redactField`](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/internal/controller/cluster/object/object.go#L591-L607)). So `references[].patchesFrom` on `status.atProvider.manifest.data[...]` cannot work by design — restoring it would reopen the leak the flag closes. We reproduced your exact error on a fresh kind cluster (provider-kubernetes v1.2.1, SA-token Secret, same manifests):

```
observe failed: cannot resolve resource references: cannot patch from referenced resource: status.atProvider.manifest.data[ca.crt]: no such field
```

## The supported pattern — verified working

Secret material should flow through **connection secrets**, which are unaffected by sanitization: `spec.connectionDetails` reads the *live* remote object (not the redacted status), and `references[].patchesFrom` can reference any resource on the control plane — including a plain `v1` Secret. Two changes:

**1. Your first Object additionally publishes the fields you need as a connection secret:**

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: my-object
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          kubernetes.io/service-account.name: secret-store-sa
        name: sa-secret
        namespace: my-namespace
      type: kubernetes.io/service-account-token
  connectionDetails:
  - apiVersion: v1
    kind: Secret
    name: sa-secret
    namespace: my-namespace
    fieldPath: data[ca.crt]
    toConnectionSecretKey: ca.crt
  - apiVersion: v1
    kind: Secret
    name: sa-secret
    namespace: my-namespace
    fieldPath: data.token
    toConnectionSecretKey: token
  writeConnectionSecretToRef:
    name: sa-token-sync
    namespace: my-namespace
  managementPolicies: ["*"]
  providerConfigRef:
    name: kubernetes-extern
```

**2. Your second Object patches from that connection secret instead of the first Object's status:**

```yaml
  references:
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: sa-token-sync
      namespace: my-namespace
      fieldPath: data[ca.crt]
    toFieldPath: spec.provider.kubernetes.server.caBundle
```

Encoding works out identically to your pre-sanitization setup: `connectionDetails` base64-decodes Secret `data` paths (to avoid double encoding), Kubernetes re-encodes at rest in the connection secret, so `data[ca.crt]` of `sa-token-sync` carries the same base64 PEM your old `status.atProvider.manifest.data["ca.crt"]` reference did.

**Verified (kind, provider-kubernetes v1.2.1, `SANITIZE_SECRETS=true`):** with these two changes the second Object goes `Synced=True / Ready=True`, the patched field is byte-identical to the source secret's `data["ca.crt"]`, and the first Object's status stays `data: {redacted: null}` throughout. We verified with a stand-in patch target; the reference mechanics are identical for your `SecretStore`.

Closing as working as designed. If the connection-details pattern doesn't cover your case, please comment and we'll reopen.
