### ISSUE TITLE
Failed to install Provider on GKE cluster - cannot establich control of object: cannot deploy a CRD with webhook conversion strategy without having a TLS bundle

### ISSUE THREAD

**Issue by gusfcarvalho** [crossplane-contrib/provider-kubernetes#270]
### What happened?

When installing the provider within a GKE cluster, it fails to install with the following error message:
```
Events:
  Type     Reason             Age                 From                                         Message
  ----     ------             ----                ----                                         -------
  Normal   BindClusterRole    23m (x6 over 30m)   rbac/providerrevision.pkg.crossplane.io      Bound system ClusterRole to provider ServiceAccount(s)
  Normal   ApplyClusterRoles  23m (x3 over 30m)   rbac/providerrevision.pkg.crossplane.io      Applied RBAC ClusterRoles
  Warning  SyncPackage        29s (x37 over 30m)  packages/providerrevision.pkg.crossplane.io  cannot establish control of object: cannot deploy a CRD with webhook conversion strategy without having a TLS bundle
```
I didn't find any documentation on how to troubleshoot it nor to fix it, as there isn't anything relevant on crossplane logs.
### How can we reproduce it?

I just really installed provider in the cluster:
```
cat << EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.0
EOF
```
### What environment did it happen in?
Crossplane version: v1.9.2
* Cloud provider: GCP
* Kubernetes version: v.28,90gke.1289000
* Kubernetes distribution GKE
