### ISSUE TITLE
Changing Object.spec.forProvider.manifest.metadata.name orphans previous resource

### ISSUE THREAD

**Issue by Avarei** [crossplane-contrib/provider-kubernetes#287]
### What happened?
After changing the Object.spec.forProvider.manifest.metadata.name the resource with the previous name does not get deleted.

### How can we reproduce it?
Create a Resource:
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
        name: test1
```
Change the Resource
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
        name: test2
```

run `kubectl get cm -n default` and observe both test1 and test2 are present.

### What environment did it happen in?
Provider Kubernetes: v0.14.1
Crossplane version: v1.16.0
Kubernetes: v1.28.8
