### ISSUE TITLE
Remote Object creation not working for Kubernetes-provider

### ISSUE THREAD

**Issue by dbacademy** [crossplane-contrib/provider-kubernetes#297]
### What happened?

Following error message I am getting when trying to create object into remote openshift cluster, its working perfectly with in-cluster provider config but not with remote cluster.

message: 'connect failed: cannot build kube client for provider config: cannot
  get REST config for provider: cannot create new REST config using provider secret:
  currentContext not set in kubeconfig'

### How can we reproduce it?
This is the defination of simple object to create Namespace to remoe cluster.

kind: Object
metadata:
name: sample-namespace
spec:
forProvider:
manifest:
apiVersion: v1
kind: Namespace
metadata:
# name in manifest is optional and defaults to Object name
# name: some-other-name
labels:
provisioned-by: "crossplane"
providerConfigRef:
name: providerconfig-shared-nonprod

Defination of Providerconfig

apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
name: providerconfig-shared-nonprod
spec:
credentials:
source: Secret
secretRef:
namespace: crossplane-system
name: shared-nonprod-kubeconfig
key: kubeconfig

I created a secret into conplane-system namespace where crossplae and provider is installed.

apiVersion: v1
data:
value.yaml: <base64 encoded value of kubeconfig for remote cluster>
kind: Secret
metadata:
name: shared-nonprod-kubeconfig
namespace: crossplane-system
type: Opaque

Anythig I am missing ? need help please.
Or do we have any hints how to use providerconfig with secret ref. as kubeconfig 

### What environment did it happen in?
Crossplane version: 

Client Version: v1.17.1
Server Version: v1.17.0

Client Version: 4.14.31
Kustomize Version: v5.0.1
Server Version: 4.13.49
Kubernetes Version: v1.26.15+e0953cc

**Comment by alanrichman** [comment]
@dbacademy Would you mind to share a redacted version of the kubeconfig file you are loading into the secret? Please remove any IP addresses, credentials, etc.

The error message says `currentContext not set in kubeconfig` which would indicate that you are missing the `current-context` field from the value in that secret. Here is a sample, if it helps, from my local setup for a cluster running in Docker Desktop:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [REDACTED]
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: [REDACTED]
    client-key-data: [REDACTED]
```

Try adding `current-context` with the value set to the `name` of the context you already have in the secret.
