### ISSUE TITLE
Common objet labels and annotations

### ISSUE THREAD

**Issue by fernandezcuesta** [crossplane-contrib/provider-kubernetes#311]
### What problem are you facing?
As a end user, I want to inject labels to all crossplane-managed resources. When using `provider-kubernetes` I might want to add labels or annotations to all resulting resources from Objects, so that its metadata would end up like:

```
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels:
          app.kubernetes.io/managed-by: crossplane
          foo: bar
        namespace: default
  managementPolicies:
    - Observe
  providerConfigRef:
    name: kubernetes-provider
``` 

### How could Crossplane help solve your problem?

I feel this should come directly from the ProviderConfig, e.g. under `spec.commonLabels` or by adding a new kind `ObjectTemplate` where we could set the skeleton of an Object (mainly metadata annotations and labels) from which all resulting Objects would merge.
Additionally a `selector` field could help selecting which Objects we want to alter.

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: ObjectTemplate
metadata:
  name: common
spec:
  selector: {} # applies to all Objects
  commonLabels:
    app.kubernetes.io/managed-by: crossplane
```
