### ISSUE TITLE
Support Kind List

### ISSUE THREAD

**Issue by kferrone** [crossplane-contrib/provider-kubernetes#34]
### What problem are you facing?

I wanted to make a Crossplane Kubernetes Object like this:
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: federate-list-of-stuff
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: List
      metadata:
        name: list-of-stuff
      items:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: feds-one
            namespace: default
          data:
            foo: bar
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: feds-two
            namespace: default
          data:
            peanutbutter: and jelly
```

### How could Crossplane help solve your problem?

Send all items in the list to specified cluster. Another way to encapsulate with yaml in yaml out.
In the status would be the ever familiar `references` array you would see on an XRD resource. 
Like so:
```yaml
resourceRefs:
    - apiVersion: v1
      kind: ConfigMap
      name: feds-one
      namespace: default
    - apiVersion: v1
      kind: ConfigMap
      name: feds-two
      namespace: default
```
