### ISSUE TITLE
`Object` with a broken `ConnectionDetail` reference cannot be deleted

### ISSUE THREAD

**Issue by Kidswiss** [crossplane-contrib/provider-kubernetes#345]
### What happened?

We use operators together with provider-kubernetes to deploy services.

We deploy a CR, let's call it `service`, to k8s. The operator then does its thing and creates a secret containing automatically generated credentials for `service`. We then use `spec.connectionDetails` in `Object` to expose the password via Crossplane's mechanics. So far everything works perfectly fine.

However, the issues start during deprovisioning. If the `Object` containing `service` is deleted, then the operator will also delete the secret it created. If the secret is removed by the operator, before provider-kubernetes removes the finalizer in the `Object`, then it will get stuck forever with observe errors about the broken `connectionDetail` reference.

### How can we reproduce it?

Apply these manifests:
```yaml
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: myobj
  namespace: default
spec:
  connectionDetails:
  - apiVersion: v1
    fieldPath: data[password]
    kind: Secret
    name: mysecret
    namespace: default
    toConnectionSecretKey: password
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: myobj
        namespace: default
      data: {}
  providerConfigRef:
    name: kubernetes
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
stringData:
  password: pssst
```

Then:
```
kubectl delete secrets mysecret
kubectl delete object myobj
^C
# stuck
kubectl describe object myobj
*SNIP*
Warning  CannotObserveExternalResource  4s (x5 over 20s)  managed/object.kubernetes.crossplane.io  cannot get connection details: cannot get object: secrets "mysecret" not found
```

### Expected behaviour
Provider-kubernetes shouldn't care anymore about the `connectionDetails` references, if a `deletionTimestamp` is set on the `Object`. 

### What environment did it happen in?
Provider: 0.17.0
