### ISSUE TITLE
cannot get referenced resource: secrets not found

### ISSUE THREAD

**Issue by pieterv-icloud-com** [crossplane-contrib/provider-kubernetes#348]
### What happened?
I am testing the creation of a very basic secret:

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: test-secret
spec:
  providerConfigRef:
    name: operations  
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
        name: argocd-credentials
        namespace: argocd
      stringData:
        githubAppInstallationID: githubAppInstallationID
        url: url
        githubAppID: githubAppID
        githubAppPrivateKey: githubAppPrivateKey
  references:
    - patchesFrom:
        apiVersion: v1
        kind: Secret
        name: argocd-credentials
        namespace: default                           
        fieldPath: data.githubAppInstallationID
      toFieldPath: data.githubAppInstallationID
    - patchesFrom:
        apiVersion: v1
        kind: Secret
        name: argocd-credentials
        namespace: default
        fieldPath: data.url
      toFieldPath: data.url
    - patchesFrom:
        apiVersion: v1
        kind: Secret
        name: argocd-credentials
        namespace: default
        fieldPath: data.githubAppID
      toFieldPath: data.githubAppID
    - patchesFrom:
        apiVersion: v1
        kind: Secret
        name: argocd-credentials
        namespace: default
        fieldPath: data.githubAppPrivateKey
      toFieldPath: data.githubAppPrivateKey
```

But I keep on getting the following error:

```
observe failed: cannot resolve resource references: cannot get referenced resource: secrets "argocd-credentials" not found'
```

The Kubernetes provider logs does not really give me any idea as to what is wrong either:

```
│ 2025-03-04T06:47:50.030Z    DEBUG    provider-kubernetes    Cannot observe external resource    {"controller": "managed/object.kubernetes.crossplane.io", "request": {"name":"test-secret"}, "uid": "8 │
│ b1aa1d9-0832-4168-9a9b-f4415b557420", "version": "53060", "external-name": "test-secret", "error": "cannot resolve resource references: cannot get referenced resource: secrets \"argocd-credentials\" │
│  not found", "errorVerbose": "secrets \"argocd-credentials\" not found\ncannot get referenced resource\ngithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object.(*external).resol │
│ veReferencies\n\tgithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object/object.go:679\ngithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object.(*external). │
│ Observe\n\tgithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object/object.go:354\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgith │
│ ub.com/crossplane/crossplane-runtime@v1.17.0-rc.0.0.20240513123822-e50f51abfed2/pkg/reconciler/managed/reconciler.go:914\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Recon │
│ cile\n\tgithub.com/crossplane/crossplane-runtime@v1.17.0-rc.0.0.20240513123822-e50f51abfed2/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Rec │
│ oncile\n\tsigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/contr │
│ oller-runtime@v0.17.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.17.1/pk │
│ g/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controll │
│ er.go:227\nruntime.goexit\n\truntime/asm_arm64.s:1222\ncannot resolve resource references\ngithub.com/crossplane-contrib/provider-kubernetes/internal/controller/object.(*external).Observe\n\tgithub. │
│ com/crossplane-contrib/provider-kubernetes/internal/controller/object/object.go:355\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/ │
│ crossplane-runtime@v1.17.0-rc.0.0.20240513123822-e50f51abfed2/pkg/reconciler/managed/reconciler.go:914\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com │
│ /crossplane/crossplane-runtime@v1.17.0-rc.0.0.20240513123822-e50f51abfed2/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s │
│ .io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.1 │
│ 7.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/control │
│ ler/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227\nruntime │
│ .goexit\n\truntime/asm_arm64.s:1222"} 
```

### What environment did it happen in?
Crossplane version:

**Comment by pieterv-icloud-com** [comment]
I tried another approach by creating an observe object in the local cluster:

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    crossplane.io/external-name: argocd-credentials
  name: argocd-credentials-observe
  namespace: default
spec:
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
        name: argocd-credentials
        namespace: default
      stringData:
        githubAppInstallationID: githubAppInstallationID
        url: url
        githubAppID: githubAppID
        githubAppPrivateKey: githubAppPrivateKey
  managementPolicies: ["Observe"]        
  providerConfigRef:
    name: kubernetes-provider
```

However the secret can still not be retrieved.

```
cannot resolve resource references: cannot get referenced resource: secrets "argocd-credentials" not found
```

**Comment by pieterv-icloud-com** [comment]
Went a bit further to try and diagnose this.

I can successfully observe a ConfigMap as follows:

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    crossplane.io/external-name: argocd-credentials
  name: argocd-cm-observe
  namespace: default
spec:
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        namespace: argocd
      data:
        githubAppInstallationID: githubAppInstallationID
  watch: true        
  managementPolicies: ["Observe"]        
  providerConfigRef:
    name: kubernetes-provider
```

However when I change this to a secret:

```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: argocd-credentials-test
  namespace: default
spec:
  deletionPolicy: Orphan
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-credentials
        namespace: default
      data:
        githubAppInstallationID: githubAppInstallationID
  watch: true        
  managementPolicies: ["Observe"]        
  providerConfigRef:
    name: kubernetes-provider
```

It just errors with the following:

```
managed/object.kubernetes.crossplane.io  external resource does not exist
```

**Comment by carlos-ffs** [comment]
I am having the same problem with:
```yaml
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: oidc-eks
spec:
  providerConfigRef:
    name: kubernetes-provider
  managementPolicies: ['Observe']
  forProvider:
    manifest:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: OpenIDConnectProvider
      metadata:
        name: "{{ $clusterID }}-oidc-connect-provider"
        namespace: "crossplane-system"
```

On the other hand, for the Cluster kind it works:
```yaml
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: cluster-eks
spec:
  providerConfigRef:
    name: kubernetes-provider
  managementPolicies: ['Observe']
  watch: true
  forProvider:
    manifest:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: Cluster
      metadata:
        name: "{{ $clusterID }}"
        namespace: "crossplane-system"
```
