### ISSUE TITLE
Support for ServiceAccount Token Generation via TokenRequest API

### ISSUE THREAD

**Issue by antopraveen** [crossplane-contrib/provider-kubernetes#370]
**Description:**
Currently, the provider-kubernetes supports creating Kubernetes objects such as ServiceAccount and Secret, but it lacks support for generating service account tokens using the TokenRequest API.

Starting with Kubernetes v1.24, auto-created service account tokens (via kubernetes.io/service-account-token secrets) are deprecated in favor of bound tokens created via the TokenRequest API. These tokens are short-lived and more secure, and many modern use cases (e.g., GitOps tooling, vault injection, and external systems) rely on programmatic generation of these tokens.

**Use Case:**
As a platform engineer, I want to provision a service account and generate a short-lived, bounded service account token using Crossplane so that it can be:

Mounted or injected into workloads

Shared securely with CI/CD tools

Used to authenticate to the Kubernetes API or external systems like Vault

This is especially relevant for multi-tenant, automated environments where service accounts and their credentials must be managed declaratively.

**Expected Behavior:**
A new resource type or field in the existing Object CRD to support:

Triggering a TokenRequest API call

Creating a Secret or outputting the token as a ConnectionSecret

Optionally configuring token TTL, audiences, and binding to a specific service account

**Proposed API (Example):**
```

apiVersion: kubernetes.crossplane.io/v1alpha2
kind: ServiceAccountTokenRequest
metadata:
  name: sa-token-request
spec:
  serviceAccountRef:
    name: my-app-sa
    namespace: my-namespace
  audience: my-audience
  expirationSeconds: 3600
  writeConnectionSecretToRef:
    name: my-sa-token
    namespace: crossplane-system



```
