### ISSUE TITLE
Cannot get secret when performing a patch

### ISSUE THREAD

**Issue by ChrisJBurns** [crossplane-contrib/provider-kubernetes#41]
### What happened?
I have created a cluster in AWS using Crossplane. In the same composition, I also install FluxCD onto the cluster which creates a secret with a couple of values in there. I am interested in the public key value (`identity.pub`). So I am using the kubernetes provider to try and retrieve the public key from the secret, however, it cannot be found. Currently, I'm just trying to retrieve it and put the value into a config map - just to see if secret retrieval works. Once this works, I will be attempting to output the public key value to the XR using `ToCompositeFieldPath` so I can use it in another resource (a Gitlab resource that uses the public key to create a Deploy Key)

The following error is returned when I do a describe on the resource.

```log
Events:
  Type     Reason                         Age                   From                                     Message
  ----     ------                         ----                  ----                                     -------
  Warning  CannotConnectToProvider        5m21s (x18 over 17m)  managed/object.kubernetes.crossplane.io  cannot get ProviderConfig: ProviderConfig.kubernetes.crossplane.io "default" not found
  Warning  CannotObserveExternalResource  21s (x7 over 5m4s)    managed/object.kubernetes.crossplane.io  cannot resolve resource references: cannot get referenced resource: secrets "test-vpc-sync" not found
```

### How can we reproduce it?
Have an external resource that is a secret on another cluster and then try and retrieve one of it's values.

#### Kubernetes Composition
```yaml
    - name: kubernetes
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.credentials.secretRef.namespace
      - fromFieldPath: spec.id
        toFieldPath: spec.credentials.secretRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-cluster"
      readinessChecks:
        - type: None
    - name: get-public-key
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: foo
        spec:
          references:
            - patchesFrom:
                apiVersion: v1
                kind: Secret
                name: "test-vpc-sync"
                namespace: flux-system
                fieldPath: data[identity.pub]
              toFieldPath: data.publicKey
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: flux-system
                name: pubsecret
              data:
                publicKey: sample-value
      patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.providerConfigRef.name
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.credentials.secretRef.namespace
      - fromFieldPath: spec.id
        toFieldPath: spec.credentials.secretRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-cluster"
      readinessChecks:
        - type: None
```

### What environment did it happen in?
Crossplane version:  Chart version: 1.7.1
- AWS EKS
- K8s: 1.22

**Comment by bobh66** [comment]
Did you create a kubernetes ProviderConfig for the new/target cluster and use that for the Object providerConfigRef.name so the kube provider can connect to the new cluser?

**Comment by ChrisJBurns** [comment]
Ah yes, good point, I've just added the config to the original issue :+1:

**Comment by ChrisJBurns** [comment]
So it seems after a bit of digging with @bobh66  The `Observe` functionality, does not allow you to Observe objects from a separate cluster - only the local one. In this case, can we implement this functionality?

**Comment by bobh66** [comment]
One possibility might be to add a "source" attribute to the Reference structure, with values Local or Remote (default Local) and if it is set to Remote, use c.client to retrieve the object instead of c.localclient - that seems like it would solve the immediate problem but I don't know if it raises other issues.

**Comment by ChrisJBurns** [comment]
Shall I raise a feature request officially? Or wait for someone to confirm that it is a feature request?

**Comment by bobh66** [comment]
It appears to be a little more complicated because the finalizer uses the local client to process the references and I don't think the "remote" client is immediately available to the finalizer.  So it definitely needs more analysis by someone more familiar with the internals of the provider.

**Comment by bobh66** [comment]
More specifically, the provider adds a finalizer to the referenced object, so remote object references may be problematic.

**Comment by morningspace** [comment]
> So it seems after a bit of digging with @bobh66 The [Observe functionality](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/internal/controller/object/object.go#L398), does not allow you to Observe objects from a separate cluster - only the local one. In this case, can we implement this functionality?

@ChrisJBurns Have you tried to create another `Object` to map to the remote resource so that can be handled by the k8s provider. The original purpose for the design of `references` in k8s provider is for local resources handling, mostly `Object` resources, at least for now.

Another note: IIRC, there's no special handling logic to sensitive data such as `secret` in k8s provider, e.g.: encode/decode, so, it might not solve your immediate problem.

**Comment by ChrisJBurns** [comment]
I have got this working now! Thank you @bobh66  and @morningspace 

So it's probably worth mentioning, I did try the `Observe` object between the time I raised this issue and last night when I destroyed the cluster and couldn't get it to work.

However, I've started today with a fresh new cluster and can confirm this is now working. The following code snippets will detail what the solution was in the end. But I can confirm, I am able to - using Crossplane - provision an EKS cluster, install Flux on it, use Flux to also generate a new secret containing the SSH keys (`identity`, `identity.pub` & `known_hosts`) in the new cluster, use an `Observe` object to retrieve the secret data (in my case, only the `identity.pub`(public key)). In addition to this, I am also creating a new resource in my composition that simply creates a new kubernetes secret in my new cluster with the `identity.pub` value. I am doing this just to test that I could retrieve the secret data from the `Observe` object and share it with other resources in the composition as my actual implementation will be that I pass it to a Gitlab resource which will create a deploy key (the `provider-gitlab` has yet to merge the deploy key functionality https://github.com/crossplane-contrib/provider-gitlab/pull/38). I'm sharing the key between resources in the same compositions via `CompositeField`'s.

### `Observe` object (getting of the public key)
```yaml
    - name: get-public-key
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: observesecret
        spec:
          managementPolicy: Observe
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              type: Opaque
              metadata:
                name: test-vpc-sync
                namespace: flux-system
      patches:
      - fromFieldPath: spec.id
        toFieldPath: spec.providerConfigRef.name
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.manifest.data[identity.pub]
        toFieldPath: status.publicKey
        transforms:
          - type: string
            string:
              type: Convert
              convert: FromBase64
      readinessChecks:
        - type: None
```

### Creation of new secret using the retrieve public key (will be replaced by Gitlab deploy key creation)
```yaml
    - name: new-public-key
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              type: Opaque
              metadata:
                name: public-key
                namespace: flux-system
      patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
        transforms:
          - type: string
            string:
              fmt: "%s-public-key"
      - type: FromCompositeFieldPath
        fromFieldPath: status.publicKey
        toFieldPath: spec.forProvider.manifest.data[identity.pub]
        transforms:
          - type: string
            string:
              type: Convert
              convert: ToBase64
      - fromFieldPath: spec.id
        toFieldPath: spec.providerConfigRef.name
```

Thanks all, am closing this ticket now. Feel free to add comments if you feel it's worth adding for future reference.
