### ISSUE TITLE
Private repository for the provider

### ISSUE THREAD

**Issue by jerem0808** [crossplane-contrib/provider-kubernetes#42]
### What problem are you facing?

In our contest we have to use a private docker registry.
### How could Crossplane help solve your problem?

We deployed the provider as such but the provider-kubernetes pod was still trying to reach the docker hub repo.
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "private_repo/crossplane/provider-kubernetes:main"
``` 

Would it be possible to have a "dynamic" repo?
