### ISSUE TITLE
toFieldPath not respected

### ISSUE THREAD

**Issue by LiamMccafferty-bud** [crossplane-contrib/provider-kubernetes#44]
When using k8s provider (pointing to main currently)

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "crossplane/provider-kubernetes:main"
```
  
  
  and attempting to create a k8s object from another object, The toFieldPath is not respected and the object gets created using the value of field path without the rewrite. 
  
```
  example manifest 
  
  apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: somename
  namespace: somenamespace
spec:
  references:
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: "cloudsql-instance-credentials"
      namespace: "value"
      toFieldPath: spec.forProvider.manifest.data.CLOUDSQL_INSTANCE
      fieldPath: data.cloudsql_instance_connection
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      data: 
        CLOUDSQL_INSTANCE: ""
      metadata:
        name: cloudsql
        namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: provider-kubernetes
```

```
example config map created : 

apiVersion: v1
data:
  CLOUDSQL_INSTANCE: ""
  cloudsql_instance_connection:BASE64ENCODEDVALUE==
kind: ConfigMap
metadata:
  name: cloudsql
  namespace: infra
```

when I attempt to add the toFieldPath directly to the object endpoint under Kubernetes.crossplane.io as it appears to be redacted I get
```
 objects.kubernetes.crossplane.io "nameofmyobject" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(Object.spec.references[0].patchesFrom): unknown field "toFieldPath" in io.crossplane.kubernetes.v1alpha1.Object.spec.references.patchesFrom


```
