### ISSUE TITLE
Health checks for resources

### ISSUE THREAD

**Issue by artem-nefedov** [crossplane-contrib/provider-kubernetes#45]
For our case, it's critical to be able to perform health assessment of resources created from Objects. Specifically, for custom resources compatible with [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#the-ready-condition), which essentially means "wait till the resource's status has `Ready = True` condition".

I would assume the correct implementation means the following:

- there's some way to enable health check for arbitrary Object
- if enabled, Object doesn't become ready until underlying resource reports Ready status
- Objects with dependencies (ones that have references[].dependsOn) can honor status of their dependency, regardless of whether it's another Object or an arbitrary k8s resource

I apologize if it's already possible, I didn't realize how to do it.

**Comment by morningspace** [comment]
This seems to be similar to the Composition `readinessChecks`. Will that solve your problem? Provider k8s will attach the whole manifest including status for the actual resource "managed" by `Object` to  `Object`'s status field, so you will be able to check that in Composition.

For `Object` with dependencies, there is no such `readinessChecks` in place, but you can patch something from dependencies using `patchesFrom` to mitigate this.

**Comment by artem-nefedov** [comment]
Thank you for pointing out `readinessChecks`. However, I still don't see how I can use existing readinessChecks types (MatchString, MatchInteger, NonEmpty) to work with kstatus-based conditions. In kstatus, readiness is determined by the fact that `status.conditions` array contains an element with `type: Ready` and `status: "True"`.

So, this resource is not ready:

```
status:
  conditions:
  - lastTransitionTime: "2022-06-14T11:56:12Z"
    message: Release In progress
    reason: ReconciliationInProgress
    status: InProgress
    type: Ready
```

This resource is ready:

```
status:
  conditions:
  - lastTransitionTime: "2022-06-14T11:56:35Z"
    message: Some random message
    reason: SomeRandomReason
    status: Unknown
    type: ArbitraryType
  - lastTransitionTime: "2022-06-14T11:56:35Z"
    message: Release reconciliation succeeded
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
```

I would need to check the values of 2 fields at once, and it can be present in ANY element of `conditions` array.

Same problem for dependencies.

Furthermore, the approach with redefining composition `readinessChecks` means that I will have to personally define health checks for ALL resources inside composition. If my composition consists of AWS provider resources and some Kubernetes provider Objects, I am perfectly fine with builtin health checks for AWS resources, and would prefer to be able to define health checks for Objects only.

Lastly, while not as important, being able to perform status check for dependencies not in composition would be nice.
