### ISSUE TITLE
Apply transformation when Patching from Resource

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane-contrib/provider-kubernetes#52]
I'm trying to create a k8s secret patching from another secret.

I'm trying to achieve this by applying the following object inside of a composition:

```
- name: argocd-creds-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          name: cluster-bearer-token
        spec:
          references:
          - patchesFrom:
              apiVersion: v1
              kind: Secret
              name: connection-string
              namespace: default
              fieldPath: data.kubeconfig
            toFieldPath: data.bearer-token
            transforms:
              - type: string
                string:
                  type: Regexp
                  regexp:
                    match: '(?<=token:).*$'
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                namespace: default
              data:
                sample-key: #to be patched
          providerConfigRef:
            name: local-kubernetes-provider

```

It looks like it completely ignores the transformation. 
Is the transformation taken into account at the current implementation=
