### ISSUE TITLE
Apply patch to set of existent resources

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane-contrib/provider-kubernetes#54]
We have a set of ArgoCD Application resources which are created dynamic and declaratively via the pattern (App of Apps). 
This Application.yml does have a field "cluster" which defines a cluster URL.

We want this clusterURL to map directly from an existent secret using this provider.

Is it possible based on this [example](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/object/references/patches-from-resource.yaml) for provider-kubernets to create a patch from a secret into a set of different kind of objects (finding by label or other attribute) and update a certain definition?

**Comment by ruffsandor** [comment]
I'm also facing with the issue that the references and patchesFrom concept supports only referencing by name.
As I understand since resources defined in composition have dynamic names (random hash suffix) those can not be referenced.

So how can I reference a resource having dynamic name with the patchesFrom concept?

I would be also happy if labelselector could be provided not only name

OR maybe is there a way to specify the name of an Object resource created in a composition?

AND according to the [documentation ](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/docs/enhanced-provider-k8s.md#generic-references) (is fromObject the same as patchesFrom ???) selectors should be supported, but "name" is required
spec:
  patches:
  - fromObject:
      apiVersion: ec2.aws.crossplane.io/v1alpha1
      kind: VPC
      **name: main-vpc # optional, matchLabels can be used instead.**
      fieldPath: spec.forProvider.cidrBlock
    toFieldPath: spec.cidrBlock




Solution proposal for the problem (same as suggested in the original report)

Something like:
```
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  references:
  # Use patchesFrom to patch field from other k8s resource to this object
  - patchesFrom:
      apiVersion: v1
      kind: ConfigMap
      #name: bar
      selector:
        matchLabels:
           some: label
      namespace: default
      fieldPath: data.sample-key
    toFieldPath: data.sample-key-from-bar
```
