### ISSUE TITLE
Cannot create ArgoCD application using Object resource

### ISSUE THREAD

**Issue by headyj** [crossplane-contrib/provider-kubernetes#94]
### What happened?
I try to create an ArgoCD application using Kubernetes crossplane provider (through a composition) but the application is never created. If I take the manifest and apply it directly it works so it doesn't seems related to a missconfiguration on ArgoCD side.

Nothing is logged neither on the kubernetes events nor on the provider container

### How can we reproduce it?
- create an argocd application from a kubernetes Object resource
```
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
spec:
  forProvider:
    manifest:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        labels:
          instance: my-application
        name: my-application
        namespace: argocd
      spec:
        destination:
          name: cluster-name
          namespace: my-application
        project: project-name
        source:
          path: my-application
          plugin:
            env:
              [...]
          repoURL: https://[....].git
          targetRevision: revision-name
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          retry:
            backoff:
              duration: 30s
              factor: 2
              maxDuration: 2m
            limit: 5
  managementPolicy: Observe
  providerConfigRef:
    name: provider-kubernetes
```
- application never got created. the object sync seems to be stuck:
```
  Normal  CreatedExternalResource  66s (x9 over 10m)   managed/object.kubernetes.crossplane.io  Successfully requested creation of external resource
  Normal  PendingExternalResource  65s (x17 over 10m)  managed/object.kubernetes.crossplane.io  Waiting for external resource existence to be confirmed
``` 
### What environment did it happen in?
Crossplane version: v1.10.2
Kubernetes provider version: v0.6.0
Cloud provider: AWS
Kubernetes version: v1.23-9
Kubernetes distribution: EKS
OS: Amazon Linux"
Kernel: Linux 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
